package io.worxbend.tui.core

import org.scalacheck.Gen
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.scalacheck.ScalaCheckPropertyChecks

/** Structural invariants of the generated [[WidthTable]], and the agreement between the binary search that reads it and
  * a naive scan of the same pairs.
  *
  * [[CharWidth]] decides how many columns a codepoint occupies from the *parity* of a binary-search insertion point
  * over a flat array of (start, end) pairs. That makes the file uniquely unforgiving: one integer out of order and
  * `Arrays.binarySearch` loses its precondition, after which the answer for every codepoint past that point can invert
  * — a CJK page renders one column per glyph, or a run of Latin text reserves a continuation cell it never fills.
  *
  * Nothing else in the build would notice. `WidthTable.scala` is checked in as generated output, its "do not edit by
  * hand" header is a claim no test enforces, and `tools/generate-width-table.py` fetches an unpinned `latest` UCD URL,
  * so the file cannot be regenerated byte-for-byte and diffed against its own script. These tests are the substitute:
  * they cannot tell you the table matches Unicode 17, but they can tell you it is still a well-formed sorted partition
  * and that the lookup over it is self-consistent.
  */
final class WidthTablePropertySpec extends AnyFunSuite, ScalaCheckPropertyChecks:

  implicit override val generatorDrivenConfig: PropertyCheckConfiguration =
    PropertyCheckConfiguration(minSuccessful = 500)

  private val MaxCodePoint: Int = 0x10ffff

  /** Both generated tables, named so a failure says which one broke. */
  private val tables: Seq[(String, Array[Int])] = Seq(
    ("WideRanges", WidthTable.WideRanges),
    ("AmbiguousRanges", WidthTable.AmbiguousRanges),
  )

  /** The same two, each paired with the public predicate that reads it through the binary search. */
  private val lookups: Seq[(String, Array[Int], Int => Boolean)] = Seq(
    ("WideRanges", WidthTable.WideRanges, CharWidth.isWideCodePoint),
    ("AmbiguousRanges", WidthTable.AmbiguousRanges, CharWidth.isAmbiguousCodePoint),
  )

  private def hex(codePoint: Int): String = f"U+$codePoint%04X"

  private def pairsOf(table: Array[Int]): Seq[(Int, Int)] =
    table.grouped(2).map(pair => (pair(0), pair(1))).toSeq

  /** Membership answered without the binary search — the oracle the parity trick has to reproduce. */
  private def linearScan(table: Array[Int], codePoint: Int): Boolean =
    var index = 0
    var found = false
    while !found && index < table.length do
      found = codePoint >= table(index) && codePoint <= table(index + 1)
      index += 2
    found

  test("each table is a non-empty, even-length list of (start, end) pairs"):
    tables.foreach { (name, table) =>
      assert(table.nonEmpty, s"$name is empty")
      assert(table.length % 2 == 0, s"$name holds ${table.length} integers, which is not a whole number of pairs")
    }

  test("the flat array is sorted, which is what makes a binary search over it meaningful"):
    // Arrays.binarySearch has undefined behaviour on an unsorted array: it does not fail, it answers wrongly.
    tables.foreach { (name, table) =>
      var index = 1
      while index < table.length do
        assert(table(index - 1) <= table(index), s"$name is out of order at index $index: ${hex(table(index))}")
        index += 1
    }

  test("every range is well formed, a real codepoint, and disjoint from its neighbour"):
    tables.foreach { (name, table) =>
      var index = 0
      while index < table.length do
        val first = table(index)
        val last  = table(index + 1)
        assert(first <= last, s"$name pair at $index runs backwards: ${hex(first)}..${hex(last)}")
        assert(first >= 0, s"$name pair at $index starts below zero: ${hex(first)}")
        assert(last <= MaxCodePoint, s"$name pair at $index ends past the last codepoint: ${hex(last)}")
        if index + 2 < table.length then
          // a touching pair (last + 1 == next start) is two ranges the generator failed to merge, and a merged table
          // is the only one a reader can compare against the UCD by eye
          assert(
            table(index + 2) > last + 1,
            s"$name range ${hex(first)}..${hex(last)} touches the next, which starts ${hex(table(index + 2))}",
          )
        index += 2
    }

  test("Wide and Ambiguous never claim the same codepoint"):
    // East Asian Width is a partition: a codepoint is W/F, or A, or neither. A codepoint in both tables means the
    // generator misread a UCD line, and because `baseWidth` consults Wide first the mistake would stay silent.
    val ambiguousPairs = pairsOf(WidthTable.AmbiguousRanges)
    pairsOf(WidthTable.WideRanges).foreach { (wideStart, wideEnd) =>
      ambiguousPairs.foreach { (ambiguousStart, ambiguousEnd) =>
        assert(
          wideEnd < ambiguousStart || ambiguousEnd < wideStart,
          s"wide ${hex(wideStart)}..${hex(wideEnd)} overlaps ambiguous ${hex(ambiguousStart)}..${hex(ambiguousEnd)}",
        )
      }
    }

  test("the binary search agrees with a linear scan on every range boundary"):
    // Random sampling will not land on a boundary in a space of 1.1 million codepoints, and a boundary is precisely
    // where an off-by-one in the parity rule shows up, so this walks all ~600 of them plus each neighbour.
    lookups.foreach { (name, table, member) =>
      table.foreach { boundary =>
        Seq(boundary - 1, boundary, boundary + 1)
          .filter(codePoint => codePoint >= 0 && codePoint <= MaxCodePoint)
          .foreach { codePoint =>
            assert(
              member(codePoint) == linearScan(table, codePoint),
              s"$name: binary search and linear scan disagree at ${hex(codePoint)}",
            )
          }
      }
    }

  test("the binary search agrees with a linear scan on sampled codepoints"):
    forAll(Gen.choose(0, MaxCodePoint)) { codePoint =>
      assert(
        CharWidth.isWideCodePoint(codePoint) == linearScan(WidthTable.WideRanges, codePoint),
        s"WideRanges disagrees at ${hex(codePoint)}",
      )
      assert(
        CharWidth.isAmbiguousCodePoint(codePoint) == linearScan(WidthTable.AmbiguousRanges, codePoint),
        s"AmbiguousRanges disagrees at ${hex(codePoint)}",
      )
    }

  test("codepoints whose East Asian Width is settled land in the table they belong to"):
    // The structural tests above are all self-referential: they compare the table against itself. These are the
    // anchors that tie it to Unicode, spread across the blocks a stray integer would drag with it.
    val wide      = Seq(0x1100, 0x3042, 0x4e00, 0x6f22, 0xac00, 0xff01, 0x1f600, 0x20000)
    wide.foreach(codePoint => assert(CharWidth.isWideCodePoint(codePoint), s"${hex(codePoint)} should be wide"))
    val notWide   = Seq(0x0041, 0x00e9, 0x0301, 0x2500, 0x2764, 0x1f1e6, 0x10000)
    notWide.foreach(codePoint => assert(!CharWidth.isWideCodePoint(codePoint), s"${hex(codePoint)} should not be wide"))
    val ambiguous = Seq(0x00a1, 0x00b1, 0x00d7, 0x0391, 0x0410, 0x2500, 0x25a0)
    ambiguous.foreach(codePoint =>
      assert(CharWidth.isAmbiguousCodePoint(codePoint), s"${hex(codePoint)} should be ambiguous")
    )

  test("the tables decide real widths, not just their own membership"):
    // The lookup only matters through `CharWidth.of`, so at least one codepoint from each table has to be shown
    // arriving at the column count the table implies — under both width modes, since that is the one knob.
    assert(CharWidth.of("漢") == 2)
    assert(CharWidth.of("漢", WidthMode.Wide) == 2)
    assert(CharWidth.of("a") == 1)
    assert(CharWidth.of("─", WidthMode.Narrow) == 1)
    assert(CharWidth.of("─", WidthMode.Wide) == 2)
