#!/usr/bin/env python3
"""Generate WorldTable.scala from world coastline coordinates.

The coordinates are the public-domain world coastline dataset published at
http://www.gnuplotting.org/plotting-the-world-revisited, itself derived from
Natural Earth (public domain, CC0). They are geographic measurements — where
the world's coastlines are — rather than authored content, and the same two
sampled outlines (a ~1000-point one and a ~5000-point one) are what every
terminal-UI toolkit that draws a world map uses.

Input format: one point per line, "<longitude> <latitude>" in decimal degrees,
EPSG:4326, in the order the outline should be walked. Blank lines and lines
beginning with '#' are ignored. Run it once per resolution:

    python3 tools/generate-world-table.py \\
        --low world-low.txt --high world-high.txt \\
        --output widgets/src/main/scala/io/worxbend/tui/widgets/WorldTable.scala

WHY THE ENCODING IS NOT A LIST OF DOUBLES
-----------------------------------------
Five thousand points is ten thousand numbers, and a `Array(1.0, 2.0, ...)`
literal of that size is emitted as ten thousand bytecode instructions in the
class initializer, which overruns the JVM's 64 KB per-method limit. Each
coordinate is therefore quantized to 15 bits and packed one per `Char` into
string constants, which the JVM stores in the constant pool rather than as
code, and decoded once into an `Array[Double]` on first use.

Two details of that packing matter:

  * 15 bits is 32768 steps, so longitude resolves to 360/32767 = 0.011 degrees
    and latitude to 180/32767 = 0.0055 degrees. One braille dot on a canvas
    spanning the whole globe is about 0.36 degrees wide, so the quantization is
    more than an order of magnitude below anything that can be drawn.
  * every packed value is biased by 0x100, putting the whole range in
    0x0100..0x80FF. That keeps it clear of both the C0 control characters at the
    bottom and the UTF-16 surrogate range at 0xD800..0xDFFF, which is not a
    valid lone character in a Scala string literal.
"""

import argparse
from pathlib import Path

# 15-bit quantization, biased clear of the control characters and the surrogate range.
STEPS = 32767
BIAS = 0x100
# Values per emitted string literal. Chosen so a generated line stays a few thousand
# characters rather than tens of thousands: a constant-pool entry is capped at 65535
# bytes of modified UTF-8, and a shorter line is one a reviewer can at least scroll past.
CHUNK = 480

BANNER = '''package io.worxbend.tui.widgets

/** The world's coastlines as interleaved longitude/latitude pairs in EPSG:4326 degrees.
  *
  * GENERATED by `tools/generate-world-table.py` from the public-domain world coastline dataset published at
  * http://www.gnuplotting.org/plotting-the-world-revisited (derived from Natural Earth, CC0) — do not edit by hand;
  * regenerate from the source coordinates instead.
  *
  * Each coordinate is quantized to 15 bits and packed one per `Char` into the string constants below, then decoded once
  * into an `Array[Double]` on first use. A literal array of ten thousand doubles would be ten thousand bytecode
  * instructions in the class initializer, which overruns the JVM's 64 KB per-method limit; string constants live in the
  * constant pool instead. The quantization resolves longitude to 0.011 degrees and latitude to 0.0055 degrees, more
  * than an order of magnitude finer than one braille dot on a canvas spanning the whole globe. Every packed value is
  * biased by 0x100, which keeps the range clear of the control characters and of the UTF-16 surrogate range.
  *
  * Immutable after the first read and safe to share between threads; the arrays are never handed outside this module.
  */
private[widgets] object WorldTable:
'''


def read_points(path):
    points = []
    for line in Path(path).read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        longitude, latitude = stripped.split()
        points.append((float(longitude), float(latitude)))
    return points


def quantize(value, minimum, maximum):
    fraction = (value - minimum) / (maximum - minimum)
    step = round(min(1.0, max(0.0, fraction)) * STEPS)
    return step + BIAS


def encode(points):
    chunks = []
    values = []
    for longitude, latitude in points:
        values.append(quantize(longitude, -180.0, 180.0))
        values.append(quantize(latitude, -90.0, 90.0))
    for start in range(0, len(values), CHUNK):
        escaped = "".join(f"\\u{value:04x}" for value in values[start:start + CHUNK])
        chunks.append(escaped)
    return chunks


def emit_chunks(name, chunks):
    lines = [f"  private val {name}: Array[String] = Array("]
    for chunk in chunks:
        lines.append(f'    "{chunk}",')
    lines.append("  )")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--low", required=True, help="coordinates for MapResolution.Low")
    parser.add_argument("--high", required=True, help="coordinates for MapResolution.High")
    parser.add_argument("--output", required=True, help="Scala file to write")
    args = parser.parse_args()

    low = read_points(args.low)
    high = read_points(args.high)
    body = [
        BANNER,
        emit_chunks("lowChunks", encode(low)),
        "",
        emit_chunks("highChunks", encode(high)),
        "",
        f"  /** The lower-detail outline: {len(low)} points, right for a small pane. */",
        "  lazy val low: Array[Double] = decode(lowChunks)",
        "",
        f"  /** The higher-detail outline: {len(high)} points, right for a full-screen braille canvas. */",
        "  lazy val high: Array[Double] = decode(highChunks)",
        "",
        "  /** Unpacks the quantized chunks back into interleaved longitude/latitude degrees. */",
        "  private def decode(chunks: Array[String]): Array[Double] =",
        "    val out   = new Array[Double](chunks.foldLeft(0)(_ + _.length))",
        "    var index = 0",
        "    chunks.foreach { chunk =>",
        "      var position = 0",
        "      while position < chunk.length do",
        f"        val step = chunk.charAt(position).toInt - 0x{BIAS:x}",
        "        // even entries are longitudes over 360 degrees, odd ones latitudes over 180",
        f"        out(index) = if index % 2 == 0 then step * 360.0 / {STEPS} - 180.0 else step * 180.0 / {STEPS} - 90.0",
        "        index += 1",
        "        position += 1",
        "    }",
        "    out",
        "",
    ]
    Path(args.output).write_text("\n".join(body))
    print(f"wrote {args.output}: {len(low)} low points, {len(high)} high points")


if __name__ == "__main__":
    main()
