#!/usr/bin/env python3
"""Generate WidthTable.scala from the Unicode Character Database.

Downloads EastAsianWidth.txt (latest UCD) and extracts two sets of codepoint
ranges: those whose East Asian Width is Wide (W) or Fullwidth (F), which every
terminal renders two columns wide, and those whose width is Ambiguous (A),
which a Western-locale terminal renders one column wide and a CJK-locale one
renders two. Contiguous ranges are merged and both sets are emitted as sorted
lookup tables in one Scala source file.

The table is standards-derived data — the lookup logic that
consumes it lives in CharWidth.scala and is original code.

Usage: python3 tools/generate-width-table.py
"""

import re
import urllib.request
from pathlib import Path

UCD_URL = "https://unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt"
OUTPUT = Path(__file__).resolve().parent.parent / "core/src/main/scala/io/worxbend/tui/core/WidthTable.scala"

LINE_RE = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)")


def fetch() -> str:
    with urllib.request.urlopen(UCD_URL) as response:
        return response.read().decode("utf-8")


def merge(ranges: list[tuple[int, int]]) -> list[tuple[int, int]]:
    """Sort inclusive (start, end) pairs and fuse the ones that touch or overlap."""
    ranges.sort()
    merged: list[tuple[int, int]] = []
    for start, end in ranges:
        if merged and start <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], end))
        else:
            merged.append((start, end))
    return merged


def parse_ranges(text: str) -> tuple[list[tuple[int, int]], list[tuple[int, int]], str]:
    """Return (wide, ambiguous, version). Only lines the file states explicitly are read,
    exactly as before: the @missing defaults are deliberately not expanded."""
    wide: list[tuple[int, int]] = []
    ambiguous: list[tuple[int, int]] = []
    version = "unknown"
    for line in text.splitlines():
        if line.startswith("#") and "EastAsianWidth" in line and version == "unknown":
            version = line.lstrip("# ").strip()
        match = LINE_RE.match(line)
        if not match:
            continue
        start = int(match.group(1), 16)
        end = int(match.group(2), 16) if match.group(2) else start
        width = match.group(3)
        if width in ("W", "F"):
            wide.append((start, end))
        elif width == "A":
            ambiguous.append((start, end))
    return merge(wide), merge(ambiguous), version


def format_pairs(ranges: list[tuple[int, int]]) -> str:
    return "\n".join(f"    0x{s:05x}, 0x{e:05x}," for s, e in ranges)


def emit(wide: list[tuple[int, int]], ambiguous: list[tuple[int, int]], version: str) -> str:
    wide_pairs = format_pairs(wide)
    ambiguous_pairs = format_pairs(ambiguous)
    return f"""package io.worxbend.tui.core

/** Codepoint ranges by East Asian Width, the property that decides how many terminal columns a character occupies.
  *
  * GENERATED by `tools/generate-width-table.py` from {version} — do not edit by hand;
  * regenerate against a newer UCD instead. Each array is a flat sorted list of inclusive
  * (start, end) pairs, consumed by [[CharWidth]] via binary search.
  */
private[core] object WidthTable:

  /** Codepoints with East Asian Width `W` (Wide) or `F` (Fullwidth): two columns in every terminal. */
  val WideRanges: Array[Int] = Array(
{wide_pairs}
  )

  /** Codepoints with East Asian Width `A` (Ambiguous): one column in a Western-locale terminal and two in a
    * CJK-locale one. Box drawing, Greek and Cyrillic letters, the arrow block, `±` and `×` are all in here.
    */
  val AmbiguousRanges: Array[Int] = Array(
{ambiguous_pairs}
  )
"""


def main() -> None:
    text = fetch()
    wide, ambiguous, version = parse_ranges(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(emit(wide, ambiguous, version))
    print(f"{version}: {len(wide)} merged wide, {len(ambiguous)} merged ambiguous ranges -> {OUTPUT}")


if __name__ == "__main__":
    main()
