#!/usr/bin/env python3
"""Generate WidthTable.scala from the Unicode Character Database.

Downloads EastAsianWidth.txt (latest UCD), extracts the codepoint ranges whose
East Asian Width is Wide (W) or Fullwidth (F), merges contiguous ranges, and
emits a sorted lookup table as Scala source.

The table is standards-derived data — the lookup logic that
consumes it lives in CharWidth.scala and is original code.

Usage: python3 tools/generate-width-table.py
"""

import re
import urllib.request
from pathlib import Path

UCD_URL = "https://unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt"
OUTPUT = Path(__file__).resolve().parent.parent / "core/src/main/scala/io/worxbend/tui/core/WidthTable.scala"

LINE_RE = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)")


def fetch() -> str:
    with urllib.request.urlopen(UCD_URL) as response:
        return response.read().decode("utf-8")


def parse_wide_ranges(text: str) -> list[tuple[int, int]]:
    ranges = []
    version = "unknown"
    for line in text.splitlines():
        if line.startswith("#") and "EastAsianWidth" in line and version == "unknown":
            version = line.lstrip("# ").strip()
        match = LINE_RE.match(line)
        if not match:
            continue
        start = int(match.group(1), 16)
        end = int(match.group(2), 16) if match.group(2) else start
        width = match.group(3)
        if width in ("W", "F"):
            ranges.append((start, end))
    ranges.sort()
    merged: list[tuple[int, int]] = []
    for start, end in ranges:
        if merged and start <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], end))
        else:
            merged.append((start, end))
    return merged, version


def emit(ranges: list[tuple[int, int]], version: str) -> str:
    pairs = "\n".join(f"    0x{s:05X}, 0x{e:05X}," for s, e in ranges)
    return f"""package io.worxbend.tui.core

/** Codepoint ranges with East Asian Width `W` (Wide) or `F` (Fullwidth).
  *
  * GENERATED by `tools/generate-width-table.py` from {version} — do not edit by hand;
  * regenerate against a newer UCD instead. Flat sorted array of inclusive
  * (start, end) pairs, consumed by [[CharWidth]] via binary search.
  */
private[core] object WidthTable:

  val WideRanges: Array[Int] = Array(
{pairs}
  )
"""


def main() -> None:
    text = fetch()
    ranges, version = parse_wide_ranges(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(emit(ranges, version))
    print(f"{version}: {len(ranges)} merged wide ranges -> {OUTPUT}")


if __name__ == "__main__":
    main()
